### ISSUE TITLE
update to futures 0.3

### ISSUE THREAD

**Issue by alexmo1997** [http-rs/surf#100]
Now that async/await is stable, futures 0.3 and async-std 1.0 is released, it would be nice to be able to use surf with all these new stable versions of those projects.

**Comment by yoshuawuyts** [comment]
@alexmo1997 fully agree; this would be considered a breaking change though, so I've marked it as part of the "2.0" release. Thanks for raising this!

**Comment by yoshuawuyts** [comment]
We're currently waiting on `isahc` to upgrade before we can move over. Probably should start putting in the work in anticipation though; although I don't expect it to be that much.

https://github.com/sagebind/isahc/issues/125
