### ISSUE TITLE
Documentation of installing this package is assuming cargo-edit to be pre-installed

### ISSUE THREAD

**Issue by mustafapc19** [http-rs/surf#102]
For a beginner to rust I think installation should say to install cargo-edit. I am using cargo 1.38.0 Ubuntu 19.10.

**Comment by mustafapc19** [comment]
And why doesnt this have 'cargo install'? I am pretty new to this so pardon any stupidness

**Comment by yoshuawuyts** [comment]
@mustafapc19 no worries; you're right that we should have better instructions here. We could probably copy the "with `cargo-edit` installed" instructions from `async-std`: https://github.com/async-rs/async-std/#installation. If you'd like to submit a patch for that it'd be very welcome!

**Comment by mustafapc19** [comment]
Yeah. I'll submit the patch right away

**Comment by goto-bus-stop** [comment]
Fixed in #103, thanks!
