### ISSUE TITLE
Unable to reuse Client with Request

### ISSUE THREAD

**Issue by pnehrer** [http-rs/surf#109]
While I can create a Request and populate it, I am unable to "execute" it using an existing Client instance.

I can reuse a Client instance by creating Requests directly from it, but that requires re-parsing of the url, which could panic.

Ideally I could call Request::new() with a pre-parsed url, further populate the request, then execute it using an existing Client instance.

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/issues/192 proposes api changes that, I believe, also deal with this.

**Comment by goto-bus-stop** [comment]
I believe that #194 has addressed this. Thanks!
