### ISSUE TITLE
static-curl

### ISSUE THREAD

**Issue by gmosx** [http-rs/surf#112]
Thanks for the great library.

I am wondering is away to avoid dependence to `libcurl.so` by statically including curl support?

**Comment by yoshuawuyts** [comment]
@gmosx it's definitely possible; `isahc` links curl statically [by default](https://github.com/sagebind/isahc/blob/master/Cargo.toml#L21). But from talking to the `libcurl` maintainers they highly recommend linking dynamically (as it will fall back to static linking if it's not found).

There should be a way of specifying nested deps by doing something like `http-client-native/http-client-curl/isahc/static-curl`. But perhaps we should enable a flag for this?

Out of curiosity: what purpose do you have in mind that you'd like to statically link?

**Comment by gmosx** [comment]
I was trying to build a docker container based on scratch and/or alpine and had some issues with libcurl.so. Could only get a container based on Ubuntu to work. I am wondering if there is an example Dockerfile to run a simple service that uses surf to fetch some data.

**Comment by yoshuawuyts** [comment]
I don't have any; but I was under the impression that pulling in curl using alpine should be pretty straight forward:

```sh
$ apk add libcurl
```

Though I've never tried it myself with Rust myself. Unfortunately we currently don't have a docker example either; but if you figure it out we'd love to know for future reference!

**Comment by gmosx** [comment]
That didn't work for me. Will investigate it some more. Thanks and keep up the good work!

**Comment by yoshuawuyts** [comment]
@gmosx did you manage to make any progress on this?

**Comment by tarkah** [comment]
I was able to get curl to statically link in my binary by adding the following line in my dependencies, along with surf (I actually use http-client directly, but I'd imagine it makes no difference).

`curl = { version = "0.4", default-features=false, features = ["static-curl", "static-ssl", "http2"] }`

I confirmed this worked by installing libcurl-devel locally so it'd use dynamic linking when built, building the binary without that dependency line, and confirmed libcurl was being dynamically linked. After adding that line, libcurl was no longer dynamically linked in the binary. It also works with statically linking openssl.

**Comment by yoshuawuyts** [comment]
@tarkah thanks for sharing that solution! Perhaps we should document that as part of [http-client](https://github.com/http-rs/http-client); but otherwise I think we've resolved this issue. Going to go ahead and close this. Thanks heaps all!

**Comment by gmosx** [comment]
> Perhaps we should document that as part of [http-client](https://github.com/http-rs/http-client);

That would be nice!
