### ISSUE TITLE
allow creation of client by passing native client

### ISSUE THREAD

**Issue by sehz** [http-rs/surf#120]
Currently, Surf doesn't have way to configure the client.   Instead, it would be better if we can pass configured native client.  For example
```
let native_client = HttpClient::builder()
      ... do various configuration...;
let client = surf::Client::new(native_client);
let req1 = client.get("https://httpbin.org/get").recv_string();
```

**Comment by goto-bus-stop** [comment]
There's already a doc-hidden method for this but the Client structs aren't exposed, so you cannot really use it yet:

https://github.com/http-rs/surf/blob/380c450fce2053f3b77e9726a99d741e1a33e065/src/client.rs#L43-L50

**Comment by Fishrock123** [comment]
Surf now supports client configuration as of https://github.com/http-rs/surf/releases/tag/v2.3.0
