### ISSUE TITLE
Pass `surf::Request` and `surf::Response` through middleware

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/surf#131]
Rather than passing `http::Request` and `http::Response` through the middleware, we should pass `surf::Request` and `surf::Response` through. This should significantly reduce the API surface we expose, and make it so folks no longer have to learn two different sets of APIs to write against.

**Comment by calvinbrown085** [comment]
@yoshuawuyts Hi! Would this be hard for a newcomer to pick up? Is there a place I could start looking? I'm pretty familiar with Rust syntax and libraries, but just started looking at surf :)

**Comment by goto-bus-stop** [comment]
@calvinbrown085 I think a newcomer could get pretty far with this at least! I would start by changing the signature of the `Middleware#run` trait method to use the `surf::Request` type, and letting the compiler errors tell me which other places to update.

I would expect the trickiest part to be in the [`Request#poll` implementation](https://github.com/http-rs/surf/blob/8368e88f6545e950b06e36e874c098f800a2ca47/src/request.rs#L572). That method takes ownership of some values out of the `Request` instance, _before_ running the middleware functions. It _may_ be necessary to change the ordering there (not sure, you would probably find out quick enough though...), and I don't know what lifetime issues that may cause. If you get stuck you can always ask for help in the [async-std discord](https://discord.gg/JvZeVNe).

**Comment by Fishrock123** [comment]
Unfortunately this isn't that easy to do without also moving `surf::Request` to no longer consume itself in `poll`, i.e. no longer be the holder of `middleware` or the `Future`, which causes a cascade of other necessary changes. See #192.

**Comment by Fishrock123** [comment]
PR at https://github.com/http-rs/surf/pull/194

**Comment by Fishrock123** [comment]
Completed via #194.
