### ISSUE TITLE
doesn't compile with `default-features = false`

### ISSUE THREAD

**Issue by awaited-hare** [http-rs/surf#161]
@yoshuawuyts the current state of surf is that it doesn't compile with `default-features = false`. Isn't that worthy of fixing?

_Originally posted by @tamird in https://github.com/http-rs/surf/pull/141#issuecomment-593567025_

I am in a project where I cannot linking libcurl. However I cannot disable native-client and use for example hyper client instead.

**Comment by Fishrock123** [comment]
Sounds like a pre-2.x issue
