### ISSUE TITLE
No way to iterate over response headers

### ISSUE THREAD

**Issue by jbr** [http-rs/surf#166]
There's currently no way to iterate over surf headers. I'm not sure how often this is used in practice, but example use cases might be:

- a command line tool built around surf that prints out headers in a verbose mode
- a proxy library that performs some sort of iterator transformation, such as "pass through some but not all of the headers from my upstream, depending on some predicate"
- a third party tool that wants to log or serialize information about a surf::Response

Since none of these are common needs, this also would be addressed by making surf::Response `Into<http_types::Response>` (and/or `Deref<Target=http_types::Response>`, but the case for that is less compelling)

**Comment by Fishrock123** [comment]
Fixed in https://github.com/http-rs/surf/pull/191
