### ISSUE TITLE
Implement AsRef and Into conversions between surf Requests/Responses and their inner http_types equivalents

### ISSUE THREAD

**Issue by jbr** [http-rs/surf#167]
this allows for an escape hatch to drop down to apis that might not need to be exposed at the surf level, such as header iteration (addressing #166). This would also allow for better interop between surf and tide

- [x] surf::Request -> http_types::Request
  - [x] Into
  - [x] AsRef
- [x] surf::Response -> http_types::Response
  - [x] Into
  - [x] AsRef
- [x] http_types::Response -> surf::Response (Into)
- [x] http_types::Request -> surf::Request (Into)

**Comment by Fishrock123** [comment]
I believe these are all complete.
