### ISSUE TITLE
Chat link broken?

### ISSUE THREAD

**Issue by rbtcollins** [http-rs/surf#172]
The chat link took me to https://discord.com/channels/442252698964721669/474974025454452766 aka #wg-async-ecosystem in the Rust discord, but I couldn't load any messages there, and can't switch to it from the channel switcher in my desktop client.

I'm guessing it's been retired and the README.md is stale.

**Comment by goto-bus-stop** [comment]
Ah yes, it should link to the async-std discord. Thanks!
