### ISSUE TITLE
Middleware: follow redirects

### ISSUE THREAD

**Issue by yoshuawuyts** [http-rs/surf#18]
We should write a middleware that automatically follows redirects.

**Comment by derekdreery** [comment]
You might want to mention server-side request forgery in the docs for this middleware (https://github.com/seanmonstar/reqwest/issues/680).

**Comment by yoshuawuyts** [comment]
What I think the first step to resolving this is, is to enable redirect support for GET requests without a body. That way we don't have any issues about trying to clone streams and payloads, and can safely retry without idempotency issues.

**Comment by yonkeltron** [comment]
Thanks for all the hard word!

I'd love to throw my enthusiasm behind this issue as it just bit me. Would be happy to help test this functionality out with a pre-release version or something like that. Def willing to provide feedback.

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/issues/192 also addresses things related to this, namely potential middleware re-use and non-consumption of `surf::Request`.

**Comment by yoshuawuyts** [comment]
Related discussion: https://github.com/algesten/ureq/issues/187

**Comment by Fishrock123** [comment]
#195 should have closed this
