### ISSUE TITLE
Runtime panic with alpha.3 when setting header

### ISSUE THREAD

**Issue by jamwaffles** [http-rs/surf#183]
I'm getting a panic at runtime when attempting to set a header on a `Request`. I could be misusing the library so please let me know if that's the case.

It looks like the error might be coming from [http_types::Request::insert_header](https://docs.rs/http-types/2.1.0/http_types/struct.Request.html#method.insert_header). 

I've tried `cargo clean`/`rm Cargo.lock`/`cargo build` to no avail.

The following code panics at runtime in alpha.3:

```rust
let response = surf::Request::new(method, url)
    .set_header("Content-Type", "application/json")
    .recv_json().await?;
```

The pertinent information from the backtrace appears to be this:

```
surf::request::Request<C>::set_header
    /home/james/.cargo/registry/src/github.com-1ecc6299db9ec823/surf-2.0.0-alpha.3/src/request.rs:200
```

If I comment out the `set_header` line, the request goes through (although the `recv_json` breaks now because the server doesn't respond properly).

The following code works in alpha.2:

```rust
let response = surf::Request::new(method, url)
    .set_header("Content-Type".parse().unwrap(), "application/json")
    .recv_json().await?;
```

**Comment by Licenser** [comment]
Give this a try:
```rust
let response = surf::Request::new(method, url)
    .set_header(http_types::headers::CONTENT_TYPE, "application/json")
    .recv_json().await?;
```

**Comment by jamwaffles** [comment]
Thanks for fixing this! Looking forward to the next release :)
