### ISSUE TITLE
Rename main branch to `main`?

### ISSUE THREAD

**Issue by zkat** [http-rs/surf#211]
What do y'all think? Plz no trolls

**Comment by goto-bus-stop** [comment]
Maybe we can run https://github.com/mheap/github-default-branch for the entire http-rs org?

**Comment by yoshuawuyts** [comment]
Yep, let's do it! I believe GitHub will soon release tools to make this transition easy, but if folks want to move ahead before that we can as well!

**Comment by Fishrock123** [comment]
Yeah I was thinking about this as well, I don't have any objections.

_Though I do wish github had chosen "trunk", oh well._

**Comment by goto-bus-stop** [comment]
I can do this tomorrow. We'll also need to update a bunch of references to the branch name, but it looks like that's just in readmes and not in things like action configs, so not super high stakes stuff.

One potentially annoying thing for end users is that Cargo uses the `master` branch for git dependencies by default regardless of what we configure in Github. So if folks are doing things like `surf = { git = "https://github.com/http-rs/surf.git" }` that will break.
Then again if you're depending on a branch and not a particular commit you can expect to get breaking changes without warning, and this is just one of them 😇

**Comment by zkat** [comment]
Cargo should tbh probably be patched so that it uses the remote HEAD, tbh. That seems like a pretty bad Cargo bug.

**Comment by goto-bus-stop** [comment]
It looks like that behaviour was recently changed: https://github.com/rust-lang/cargo/pull/8364
So maybe what I said isn't true anymore? I'm not sure if that PR is in a Rust release already.

**Comment by goto-bus-stop** [comment]
^ that should be all of them!
