### ISSUE TITLE
no way to get all response headers in surf 2.0.0

### ISSUE THREAD

**Issue by yshui** [http-rs/surf#212]
I can only get header values by name, using `.header()`.

surf 1.0 had `.headers()`

**Comment by yshui** [comment]
Suggestion:

Add this to `impl Response`

```rust
    pub fn headers(&self) -> impl Iterator<Item = (&HeaderName, &HeaderValues)> {
        (&self.response).into_iter()
    }
```

**Comment by Fishrock123** [comment]
@yshui Try using the main branch here:
```toml
surf = { git = "https://github.com/http-rs/surf.git", branch = "main" }
```

There should be a new alpha with all the new stuff soonish.

**Comment by yshui** [comment]
Ah, sorry, I didn't check the git version :sweat_smile:
