### ISSUE TITLE
Please make TLS support optional

### ISSUE THREAD

**Issue by joshtriplett** [http-rs/surf#219]
Sometimes, I only need http support, not https; for instance, the instance metadata services in cloud environments only need http. For such cases, I would like to be able to use surf with the async-h1 backend and no TLS stack.

**Comment by brightly-salty** [comment]
I'd like to take a swing at this and submit a PR if it would be accepted.

**Comment by Fishrock123** [comment]
Needs support in http-client. We should support this.

**Comment by Fishrock123** [comment]
@brightly-salty are you still interested in this?

I think that the `h1_client` in http-client already supports running without tls, but surf's feature flags do not.
