### ISSUE TITLE
Does surf support Dns-resolver, self-signed certificate?

### ISSUE THREAD

**Issue by flyinmind** [http-rs/surf#254]
Anyone know how to support Dns-resolver, self-signed certificate in surf? Thanks!
The two features are very useful in micro-service framework.
I searched in docs, but can't find them.

**Comment by Fishrock123** [comment]
https://github.com/http-rs/surf/releases/tag/v2.3.0 has support for setting TLS options (but only on the `h1-client`).

to use the async-h1 client: `Cargo.toml` `surf = { version: "2.3", default-features=false, features=["h1-client"] }` (or `h1-client-rustls`)
