### ISSUE TITLE
Middleware for global shared client?

### ISSUE THREAD

**Issue by aldanor** [http-rs/surf#259]
IIUC, there's no way to push anything onto the global client's middleware stack (aside from hardcoded logger middleware [here](https://github.com/http-rs/surf/blob/main/src/client.rs#L134), which serves more as an example since most users will prefer to do tracing/logging in their own way).

This means you have to choose - global/default client but no middleware, or having to pull your own client instance around just for the sake of having access to middleware, even if you use the same middleware stack everywhere?

Alternative formulation: would there be a way for `surf::get()`, `surf::post()`, etc, to make use of custom middleware?

**Comment by Fishrock123** [comment]
If this happened, it would be per-`RequestBuilder` middleware.

Otherwise, you should make your own global client with either `once_cell::sync::Lazy` or `lazy_static!`.
