### ISSUE TITLE
Client -> RequestBuilder with a user-provided Method?

### ISSUE THREAD

**Issue by aldanor** [http-rs/surf#260]
It looks like this has been oversought. How do you create a `RequestBuilder` from a `Client` (which may have a base url and the corresponding url logic) if you have a `Method` and an url?

Maybe something like `client.request(Method::Get, "foo")` would be worthwhile adding?

(There's `Client::send()`, but perhaps there might be a more ergonomic option)

**Comment by jbr** [comment]
I've run into this as well and think that we can do better than `client.send(Request::new(Method::Get, Url::parse("http://_").unwrap()).await?`

**Comment by aldanor** [comment]
@jbr Moreover, I think that's not the same thing because of the whole `base_url` logic? (this part is completely unobvious, as a matter of fact)

**Comment by jbr** [comment]
That's true — it diverges if you're using base_url

**Comment by Fishrock123** [comment]
I agree, this appears to be an oversight. 

I'd take a pr for `Client::request(&self, Method, Url) -> RequestBuilder`.

**Comment by Fishrock123** [comment]
Note: once the change described in is made, this would probably change to:
```
Client::request(&self, Method) -> RequestBuilder
```

Since `Client` would normally have a base_url set already. If this form was still needed a `request_with_url` could be introduced, although I doubt that would be necessary.

**Comment by utsavm9** [comment]
Hey! Let me know if #308 is the intended function we want to add.

**Comment by Fishrock123** [comment]
Done in #308
