### ISSUE TITLE
Can't Increase Request Timeout

### ISSUE THREAD

**Issue by tiberiusferreira** [http-rs/surf#267]
Hello, thanks for the great crate! 

The trick from https://github.com/http-rs/surf/issues/91 works for _reducing_ the timeout, but how would one increase it (from the default one used by Isahc or other backends)?

**Comment by Fishrock123** [comment]
There isn't presently an easy way, but if you are using the curl or hyper backends, something like this would work:

```rust
// https://docs.rs/isahc/0.9.13/isahc/config/trait.Configurable.html#method.timeout
let backing_client = isahc::httpClient::builder().timeout(duration).build();
// https://github.com/http-rs/http-client/blob/b7d904ffcc999baea6f69470bf59d2fb098871c7/src/isahc.rs#L24-L27
let http_client = http_client::isahc::IsahcClient::from_client(backing_client);
// https://docs.rs/surf/2.1.0/surf/struct.Client.html#method.with_http_client
let surf_client = surf::client::Client::with_http_client(http_client);
```

Sorry it's not yet nicer. :sweat:

**Comment by tiberiusferreira** [comment]
Nice, I'm glad there is a way. Thanks for the great work on Surf!
