### ISSUE TITLE
Trailing slash redirects

### ISSUE THREAD

**Issue by hipstermojo** [http-rs/surf#276]
When using the default redirect middleware on surf, I noticed that it exits early when the next redirected URL is invalid. However, I think this is recoverable if the next location is a relative URL. This was the case when surf requests a URL without a trailing slash and the server redirects to a URL with a trailing slash. I made a fix for it and wanted to know if it is worth making a PR for. I saw that something similar was mentioned in #252.

**Comment by Fishrock123** [comment]
@hipstermojo Please send a PR
