### ISSUE TITLE
"relative URL without a base" error on some websites

### ISSUE THREAD

**Issue by Shnatsel** [http-rs/surf#286]
On some websites, e.g. http://mettl.com, surf fails with the following error:

> relative URL without a base

Firefox, curl and ureq (a blocking Rust client) work fine.

16151 websites out of the top million from [Feb 3 Tranco list](https://tranco-list.eu/list/3G6L) are affected.

Tested using [this code](https://github.com/Shnatsel/rust-http-clients-smoke-test/blob/f206362f2e81521bbefb84007cdd25242f6db590/surf-smoke-test/src/main.rs). Test tool output from all affected websites: [surf-relative-url-without-base.tar.gz](https://github.com/http-rs/surf/files/6054906/surf-relative-url-without-base.tar.gz)

I've only tested the async-h1 backend; I don't know if the other backends are affected.

**Comment by Fishrock123** [comment]
`longboard GET https://mettl.com/en/` works (see https://crates.io/crates/longboard, which uses Surf), however it doesn't have a redirect option. This looks like a bug in our Redirect middleware.

**Comment by utsavm9** [comment]
With these dependencies:
```toml
[dependencies]
async-std = { version = "1.8.0", features = ["attributes"] }
surf = "2.2.0"
```
Running the linked code with `cargo run mettl.com` gives me valid output.

Is this fixed or is it hard to reproduce?

**Comment by Shnatsel** [comment]
That particular website now works, even with the original Cargo.lock used in the test. However, many websites listed in the attached archive still fail with the same error.

After running `cargo update` I'm no longer seeing this error. I am, however, seeing a lot of `Head byte length should be less than 8kb` errors in its place.

**Comment by Fishrock123** [comment]
Ok, well, we'll track that at it's issue https://github.com/http-rs/surf/issues/289
