### ISSUE TITLE
How to handle a none exist url

### ISSUE THREAD

**Issue by chen244** [http-rs/surf#311]
![image](https://user-images.githubusercontent.com/60290287/124695611-1cc6d780-df16-11eb-9a6f-0b20d3172f12.png)
Like this . I have read the doc, but I still cannot handle it..

**Comment by fiag** [comment]
```rust
let mut res = surf::get(url).await?;
if res.status() != surf::StatusCode::Ok {
    println!("Failed to download url");
}
```

**Comment by chen244** [comment]
> ```rust
> let mut res = surf::get(url).await?;
> if res.status() != surf::StatusCode::Ok {
>     println!("Failed to download url");
> }
> ```

then how to return the surf::error, now my function return a surf::Result

**Comment by chen244** [comment]
> ```rust
> let mut res = surf::get(url).await?;
> if res.status() != surf::StatusCode::Ok {
>     println!("Failed to download url");
> }
> ```

I tried, but it not help.

**Comment by Fishrock123** [comment]
Please read https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html

**Comment by chen244** [comment]
> ```rust
> let mut res = surf::get(url).await?;
> if res.status() != surf::StatusCode::Ok {
>     println!("Failed to download url");
> }
> ```
Its my code
![image](https://user-images.githubusercontent.com/60290287/124853624-c373ac80-dfd8-11eb-8d7c-d749b5825545.png)

Then it panic at "await?", before handle the url
![image](https://user-images.githubusercontent.com/60290287/124853682-e1411180-dfd8-11eb-8fac-9639cd0c39b0.png)

**Comment by jbr** [comment]
`sss` is not a valid url. Surf requires a string that can be parsed into a [`Url`](https://docs.rs/url/2.2.2/url/)

**Comment by chen244** [comment]
> `sss` is not a valid url. Surf requires a string that can be parsed into a [`Url`](https://docs.rs/url/2.2.2/url/)

This is what I need , I need to handle this error...,when people input a url or not url string, it will pop an error window

**Comment by jbr** [comment]
ahh. see the example at [`Request::new`](https://docs.rs/surf/2.2.0/surf/struct.Request.html#method.new):

```rust
use surf::http::{Url, Method};

let url = Url::parse("https://httpbin.org/get")?;
let req = surf::Request::new(Method::Get, url);
```

**Comment by chen244** [comment]
> ahh. see the example at [`Request::new`](https://docs.rs/surf/2.2.0/surf/struct.Request.html#method.new):
> 
> ```rust
> use surf::http::{Url, Method};
> 
> let url = Url::parse("https://httpbin.org/get")?;
> let req = surf::Request::new(Method::Get, url);
> ```

It works, thanks
