### ISSUE TITLE
Feature: Replay the client requests

### ISSUE THREAD

**Issue by bbros-dev** [http-rs/surf#312]
Thanks for all the effort that has gone into this crate and for making it open source.

We're reviewing surf for a use case we didn't see in the doc or `examples` folders: Replaying the client requests.

Is this currently possible?  We saw the documented case showing a case where the server response is loaded to be replayed, but not the corollary.

If not currently possible, would it be within the scope of surf?

**Comment by jbr** [comment]
This seems like it should be possible but I'm not familiar with an implementation yet. The closest is [surf-vcr](https://github.com/rjframe/surf-vcr) but that's probably what you're referring to as recording the server response. I believe the same general approach should be applicable to recording the outbound request with sufficient information to replay them

**Comment by bbros-dev** [comment]
Apologies - wrong repo.  I should move it?
