### ISSUE TITLE
Wrong config for feature?

### ISSUE THREAD

**Issue by aadi-pcln** [http-rs/surf#326]
Hi Folks,

First, thank you for making Surf.  It's really been quite a pleasure to use.

I believe I've discovered an error in feature configuration, when I was trying to get at the `set_tls_config` function while trying to use the `h1-client` with `native-tls` support.

It looks like the feature configuration is mistyped as `h1_client` when all other references are `h1-client`.  Happy to open a PR but I wanted to confirm this was an actual issue and not intentional.

Please see here:
https://github.com/http-rs/surf/blob/main/src/config.rs#L206

Thanks!

**Comment by Fishrock123** [comment]
Fixed by https://github.com/http-rs/surf/pull/327 ... release still todo

**Comment by Fishrock123** [comment]
Released 2.3.2 https://github.com/http-rs/surf/releases/tag/v2.3.2
