### ISSUE TITLE
Can't compile to wasm with the `native-client` (or `hyper-client`) feature active

### ISSUE THREAD

**Issue by CryZe** [http-rs/surf#42]
When the `native-client` and / or `hyper-client` feature is active, the crate does not compile to wasm anymore.

**Comment by yoshuawuyts** [comment]
@CryZe could you say more? Do you mean when disabling the default features, and re-enabling the `native-client` features?

**Comment by CryZe** [comment]
I have both the hyper-client and wasm-client feature active and the crate stops compiling to WebAssembly when this is the case.

**Comment by yoshuawuyts** [comment]
@CryZe oh that's no good indeed!

> (Although even when that's not the case I'm having trouble using surf at all on wasm).

Could you say more? I know it's not the best impl quite yet, but having some more pointers on what's going wrong would give us a chance to fix it! (:

**Comment by mmstick** [comment]
Trying to use this in a crate that other applications will import as a dependency, but this causes the crate to either only be compatible with native, or only be compatible with wasm, depending on which features the crate imports it. I don't think the wasm feature should be a crate feature. You can define target-specific dependencies in Cargo.toml with cfgs, and do the same in the source code as is already being done matching on the wasm-client feature.

**Comment by Fishrock123** [comment]
`native-client` no longer exists in 2.0, and `hyper-client` re-addition is in PR: https://github.com/http-rs/surf/pull/234

If you want to use wasm, the `wasm-client` feature flag is now required.

**Comment by mmstick** [comment]
The point is that there shouldn't be a `wasm-client` feature flag because that makes any crate that uses `surf` to either be exclusive to WASM or exclusive to native.
