### ISSUE TITLE
InvalidData errors are unhelpful

### ISSUE THREAD

**Issue by liamcurry** [http-rs/surf#62]
When deserializing JSON fails a `std::io::ErrorKind::InvalidData` is returned. While this is technically accurate it isn't very useful. `serde` provides very useful error messages so it would be nice if those were available somehow.

**Comment by yoshuawuyts** [comment]
@liamcurry ohh, yeah that *would* be great. Do you have any suggestions how we could better go about this? I'm not sure how to get the messages?

**Comment by k-nasa** [comment]
Isn't the information increasing just by making it an exception?

```rust
    pub async fn body_json<T: DeserializeOwned>(&mut self) -> std::io::Result<T> {
        let body_bytes = self.body_bytes().await?;
        Ok(serde_json::from_slice(&body_bytes).map_err(|_| std::io::ErrorKind::InvalidData)?)
    }
```

```rust
    pub async fn body_json<T: DeserializeOwned>(&mut self) -> Result<T, Exception> {
        let body_bytes = self.body_bytes().await?;
        Ok(serde_json::from_slice(&body_bytes)?)
    }
```

**Comment by taiki-e** [comment]
[`std::io::Error::new`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#method.new) is probably more preferable.

```rust
    pub async fn body_json<T: DeserializeOwned>(&mut self) -> std::io::Result<T> {
        let body_bytes = self.body_bytes().await?;
        serde_json::from_slice(&body_bytes)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))
    }
```

**Comment by goto-bus-stop** [comment]
Looks like this was fixed in https://github.com/http-rs/surf/pull/85. Thanks!
