### ISSUE TITLE
Allow ?Sized arguments to request methods

### ISSUE THREAD

**Issue by IslandUsurper** [http-rs/surf#76]
I'm migrating from reqwest because I want my library to be used in WASM or native, and one of things that has bitten me is that `Request::set_query()` and `Request::body_json()` require their parameters to be `Sized`. A few of the requests I make pass in `&[&str]` which gets encoded as JSON. Serde handles this fine, and both Surf and reqwest call `serde_json::to_vec()`.

Is it possible to modify `body_form()`, `body_json()`, and `set_query()` to take a `&impl Serialize + ?Sized` parameter?

**Comment by k-nasa** [comment]
Is this what you wanted to do?　https://github.com/rustasync/surf/pull/77
If possible, please show me the code I wanted to run
