### ISSUE TITLE
How to set request timeout?

### ISSUE THREAD

**Issue by feymartynov** [http-rs/surf#91]
Didn't find anything on timeouts in docs or sources. Is there a way to get an error after waiting for the response after the given duration?

**Comment by yoshuawuyts** [comment]
You can use [`future::timeout`](https://docs.rs/async-std/0.99.11/async_std/future/fn.timeout.html) for this.

**Comment by feymartynov** [comment]
Is [`futures_timer::Delay`](https://docs.rs/futures-timer/1.0.3/futures_timer/) together with [`futures::future::select`](https://docs.rs/futures/0.3.1/futures/future/fn.select.html) also an option?

**Comment by yoshuawuyts** [comment]
@feymartynov yeah, that should work

**Comment by feymartynov** [comment]
OK, thanks!

**Comment by eigenein** [comment]
Just sharing the middleware snippet since I came here from Google (`2.0.0-alpha.5`):

```rust
pub fn default_request_timeout(request: Request, client: Client, next: Next) -> BoxFuture<surf::Result<Response>> {
    const REQUEST_TIMEOUT: Duration = Duration::from_secs(30);
    Box::pin(async move { async_std::future::timeout(REQUEST_TIMEOUT, next.run(request, client)).await? })
}
```

**Comment by MCOfficer** [comment]
does using futures::timout close the underlying streams? I'm doing a lot of concurrent requests, and within seconds i run into errors like this one:

```
thread 'async-std/runtime' panicked at 'called `Result::unwrap()` on an `Err` value: Io(x17:32:01 [WARN] request completed with error: ResponseBodyError(None): unknown error
Os { code: 24, kind: Other, message: "Too many open files" })', /home/florian/.cargo/registry/srx17:32:01 [WARN] request completed with error: ResponseBodyError(None): unknown error
c/github.com-1ecc6299db9ec823/http-client-4.0.0/src/isahc.rs:25:52 
```

I have parallelism limited to 8 and made sure i have a reasonable open files limit, so my best guess is that streams are somehow staying open.

**Comment by cryptogohan** [comment]
Can't say I'm enjoying the experience:
```rust
let five_seconds = Duration::from_secs(5);
let request_f = surf::get(uri).recv_json();
let prices: HashMap<String, MultiPrice> = future::timeout(five_seconds, request_f)
    .await
    .map_err(|error| surf::Error::new(StatusCode::RequestTimeout, error))
    .and_then(|x| x)?;
```

Suggestions for how to do this more cleanly? 😬

**Comment by Fishrock123** [comment]
Please see https://github.com/http-rs/http-client/pull/86 - Surf will eventually extend a `Config` object like this which will support things like timeouts.
