### ISSUE TITLE
`<Type> cannot be shared between threads safely` during middleware definition

### ISSUE THREAD

**Issue by zkat** [http-rs/surf#97]
I'm working on a caching middleware for Surf, and got a pretty inscrutable error. See https://gist.github.com/zkat/f9e71856bdca23eb2b665ece262db091

From a conversation in Discord, it sounds like this is because Body doesn't have a Sync bound?

**Comment by yoshuawuyts** [comment]
@zkat yeah that def seems to be the case. We should add that bound. Unsure if that's a breaking change, but we should patch this for sure.

Going to put this under the 2.0 banner just to be safe.

**Comment by Fishrock123** [comment]
Was fixed in #138
