### ISSUE TITLE
Synthetic Responses

### ISSUE THREAD

**Issue by zkat** [http-rs/surf#98]
While it's possible to craft new `Request`s with `Request::new()`, it's not currently possible to synthesize a new `Response` that can be returned from middlewares.

Being able to do this is important for [my caching middleware](https://github.com/zkat/surf-middleware-cache), because `Response`s need to be looked up in the cache and returned. In this case, I'm not even running `next.run()` when a cache hit is verified.

**Comment by zkat** [comment]
I think I messed up. It looks like you -can- do this? Feel free to close. This is just me thrashing through trying to achieve something :)

**Comment by yoshuawuyts** [comment]
@zkat hmmm, you're asking a very interesting question here. We don't allow creating a new `surf::Response`, but we *do* allow creating a new `surf::middleware::Response`. The latter which is used only inside the middleware.

Perhaps that's where the confusion came from? We should probably document this better.
